# Generated by Django 4.1.7 on 2023-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name_PC', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('time_creat', models.DateTimeField(auto_now_add=True)),
                ('stone', models.CharField(max_length=255)),
                ('wfi', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Key_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
