# Generated by Django 4.1.7 on 2023-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_date_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name_PC', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('stone', models.CharField(max_length=255)),
                ('wfi', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('time_creat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
