# Generated by Django 4.1.7 on 2023-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat', '0002_history_date_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_date_user',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
